# Generated by Django 4.1.7 on 2023-03-05 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='placetextappearance',
            options={'verbose_name': 'Miejsce wystepujące w tekście', 'verbose_name_plural': 'Miejsca występujace w tekście'},
        ),
    ]
