# Generated by Django 4.1 on 2023-05-14 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_alter_placetextappearance_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='altered_names',
        ),
        migrations.AddField(
            model_name='placetextappearance',
            name='appears_as',
            field=models.CharField(default='', max_length=100, verbose_name='występuje jako'),
        ),
        migrations.AddField(
            model_name='placetextappearance',
            name='context',
            field=models.CharField(default='', max_length=500, verbose_name='kontekst wystąpienia'),
        ),
    ]
