# Generated by Django 4.1 on 2023-05-20 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0004_remove_place_altered_names_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placetextappearance',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='text_appearances', to='places.place', verbose_name='miejsce'),
        ),
        migrations.AlterField(
            model_name='placetextappearance',
            name='role',
            field=models.PositiveSmallIntegerField(choices=[(0, 'wysłane z'), (1, 'odebrane w'), (2, 'wspomninie')], verbose_name='rola'),
        ),
    ]
