# Generated by Django 4.1.3 on 2022-11-13 16:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='', validators=[django.core.validators.FileExtensionValidator(['xml'])], verbose_name='plik')),
                ('title', models.CharField(max_length=200, verbose_name='tytuł')),
                ('publication_statement', models.CharField(max_length=1000)),
                ('source_description', models.CharField(max_length=1000, verbose_name='opis źródła')),
                ('language', models.CharField(choices=[('lat', 'łacina'), ('pl', 'polski')], max_length=3)),
            ],
            options={
                'verbose_name': 'Teskty',
                'verbose_name_plural': 'Teksty',
            },
        ),
    ]
