# Generated by Django 4.1.3 on 2022-11-13 17:57

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('texts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='text',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='data utworzenia'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='text',
            name='file',
            field=models.FileField(upload_to='texts', validators=[django.core.validators.FileExtensionValidator(['xml'])], verbose_name='plik'),
        ),
    ]
