# Generated by Django 4.1.3 on 2022-11-13 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('texts', '0002_text_created_at_alter_text_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='text',
            name='language',
            field=models.CharField(choices=[('lat', 'łacina'), ('pl', 'polski')], max_length=3, verbose_name='język'),
        ),
    ]
