# Generated by Django 4.1.3 on 2022-11-13 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('texts', '0003_alter_text_language'),
        ('persons', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='key',
            field=models.CharField(max_length=50, unique=True, verbose_name='klucz'),
        ),
        migrations.CreateModel(
            name='TextAppearance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.PositiveSmallIntegerField(choices=[(0, 'autor'), (1, 'odbiorca'), (2, 'wspomninie')])),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='persons.person', verbose_name='osoba')),
                ('text', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='texts.text', verbose_name='tekst')),
            ],
        ),
        migrations.AddField(
            model_name='person',
            name='appearance',
            field=models.ManyToManyField(through='persons.TextAppearance', to='texts.text'),
        ),
    ]
