# Generated by Django 4.1.7 on 2023-03-05 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('texts', '0003_alter_text_language'),
        ('persons', '0002_alter_person_key_textappearance_person_appearance'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonTextAppearance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.PositiveSmallIntegerField(choices=[(0, 'autor'), (1, 'odbiorca'), (2, 'wspomninie')])),
            ],
        ),
        migrations.RemoveField(
            model_name='person',
            name='appearance',
        ),
        migrations.AlterField(
            model_name='person',
            name='first_name',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='imie'),
        ),
        migrations.AlterField(
            model_name='person',
            name='last_name',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='naziwsko'),
        ),
        migrations.DeleteModel(
            name='TextAppearance',
        ),
        migrations.AddField(
            model_name='persontextappearance',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='text_appearances', to='persons.person', verbose_name='osoba'),
        ),
        migrations.AddField(
            model_name='persontextappearance',
            name='text',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appearing_persons', to='texts.text', verbose_name='tekst'),
        ),
    ]
