# Generated by Django 4.1.7 on 2023-03-05 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('texts', '0003_alter_text_language'),
        ('persons', '0003_persontextappearance_remove_person_appearance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='appearance',
            field=models.ManyToManyField(through='persons.PersonTextAppearance', to='texts.text'),
        ),
    ]
