# Generated by Django 4.1.7 on 2023-03-05 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0004_person_appearance'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='persontextappearance',
            options={'verbose_name': 'Osoba wystepujące w tekście', 'verbose_name_plural': 'Osoby wystepujące w tekście'},
        ),
    ]
