# Generated by Django 4.1 on 2023-05-14 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0006_persontextappearance_context'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='altered_names',
        ),
        migrations.AddField(
            model_name='persontextappearance',
            name='appears_as',
            field=models.CharField(default='', max_length=100, verbose_name='występuje jako'),
        ),
        migrations.AlterField(
            model_name='person',
            name='first_name',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='imię'),
        ),
        migrations.AlterField(
            model_name='person',
            name='last_name',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='nazwisko'),
        ),
        migrations.AlterField(
            model_name='persontextappearance',
            name='role',
            field=models.PositiveSmallIntegerField(choices=[(0, 'autor'), (1, 'odbiorca'), (2, 'wspomninie')], verbose_name='rola'),
        ),
    ]
